# -*- coding: utf-8 -*-
"""dataanalysisroject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/166Sj1X1HNXQo6PxaeTfy9IKItAeskpjd

# Zomato data analysis
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""#create the dataframe"""

dataframe = pd.read_csv("zomatodata.csv")
print(dataframe)

dataframe

"""#convert the data type of column Rate"""

def handleRate(value):
    value = str(value).split('/')
    value = value[0];
    return float(value)
dataframe['rate'] = dataframe['rate'].apply(handleRate)
print(dataframe.head())

dataframe.info()

"""#Type of Resturant"""

dataframe.head()

sns.countplot(x=dataframe['listed_in(type)'])
plt.xlabel("Type of Resturant")

""" conclusion - majority of the resturant falls in dining category"""

dataframe.head()

grouped_data = dataframe.groupby('listed_in(type)')['votes'].sum()
result = pd.DataFrame({'votes': grouped_data})
plt.plot(result, c="red", marker="o")
plt.xlabel("Type of Resturant", c="green", size=20)
plt.ylabel("votes", c="green", size=20)

"""conclusion - dining resturant has received maximum votes"""

dataframe.head()

plt.hist(dataframe['rate'],bins=5)
plt.title("ratings distribution")
plt.show()

"""conclusion - the majority resturant received rating from 3.5 to 4"""

dataframe.head()

"""Average order spending by couples"""

couple_data=dataframe['approx_cost(for two people)']
sns.countplot(x=couple_data)

"""conclusion - the majority of couples prefer resturant with an approximate cost of 300rs

which mode receives maximum rating
"""

dataframe.head()

plt.figure(figsize = (6,6))
sns.boxplot(x = 'online_order',y = 'rate',data = dataframe)

"""conclusion - offline order received lower rating compair to online order"""

dataframe.head()

pivot_table = dataframe.pivot_table(index='listed_in(type)', columns='online_order', aggfunc = 'size', fill_value=0)
sns.heatmap(pivot_table,annot=True,cmap="YlGnBu",fmt='d')
plt.title("Heatmap")
plt.xlabel("Online Order")
plt.ylabel("Listed In (Type)")
plt.show()

"""conclusion - Dining restaurants primarily accept offline orders , whereas cafes primarily received online orders.
This suggest that clients prefered to placed orders in person at restaurant , but prefer online ordering at cafes.
"""

